project:
  type: website
  output-dir: out
  render:
    - "README.qmd"
    - "analysis/*/*.qmd"
    - "analysis/*.qmd"
    - "*/*.qmd"
  post-render: cp -f out/README.md README.md
  resources:
    - /data/nuclear-commodity-centroids.csv
    - /data/nuclear-commodity-data.csv
    - /assets/font/*/*.pbf
    - /assets/tiles/*/*/*.pbf
    - /assets/tiles/*.json
  
# only re-render if the source changes or if we specifically render that file
execute:
  freeze: auto
